FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGhhc3RlYmluLWFwYgppbWFnZTogYW5zaWJsZXBsYXlib29rYnVu\
ZGxlL2hhc3RlYmluLWFwYgpkZXNjcmlwdGlvbjogVGhpcyBpcyBhIHNhbXBsZSBhcHBsaWNhdGlv\
biBnZW5lcmF0ZWQgYnkgYXBiIGluaXQKYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbApt\
ZXRhZGF0YToKICBkaXNwbGF5TmFtZTogSGFzdGViaW4gKEFQQikKICBkZXBlbmRlbmNpZXM6IFsn\
ZG9ja2VyLmlvL2R5bXVycmF5L2hhc3RlYmluOmxhdGVzdCcsICdkb2NrZXIuaW8vbW9kdWxhcml0\
eWNvbnRhaW5lcnMvbWVtY2FjaGVkOmxhdGVzdCddCiAgcHJvdmlkZXJEaXNwbGF5TmFtZTogIlJl\
ZCBIYXQsIEluYy4iCnBsYW5zOgogIC0gbmFtZTogZGVmYXVsdAogICAgZGVzY3JpcHRpb246IFRo\
aXMgZGVmYXVsdCBwbGFuIGRlcGxveXMgaGFzdGViaW4tYXBiCiAgICBmcmVlOiBUcnVlCiAgICBt\
ZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6CiAgICAgIC0gbmFtZTogaGFzdGViaW5fcG9ydAog\
ICAgICAgIHR5cGU6IGludAogICAgICAgIGRlZmF1bHQ6IDc3NzcKICAgICAgICB0aXRsZTogSGFz\
dGViaW4gUG9ydAogICAgICAtIG5hbWU6IG1heF9sZW5ndGgKICAgICAgICB0eXBlOiBpbnQKICAg\
ICAgICBkZWZhdWx0OiA0MDAwMDAKICAgICAgICB0aXRsZTogTWF4IGxlbmd0aCBvZiBoYXN0ZWJp\
biBlbnRyeQogICAgICAtIG5hbWU6IGtleV9sZW5ndGgKICAgICAgICB0eXBlOiBpbnQKICAgICAg\
ICBkZWZhdWx0OiAxMAogICAgICAgIHRpdGxlOiBMZW5ndGggb2YgaGFzdGViaW4ga2V5Cg=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
